#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : tempest-lib
Version  : 0.9.0
Release  : 11
URL      : http://tarballs.openstack.org/tempest-lib/tempest-lib-0.9.0.tar.gz
Source0  : http://tarballs.openstack.org/tempest-lib/tempest-lib-0.9.0.tar.gz
Summary  : OpenStack Functional Testing Library
Group    : Development/Tools
License  : Apache-2.0
Requires: tempest-lib-bin
Requires: tempest-lib-python
BuildRequires : fixtures-python
BuildRequires : httplib2
BuildRequires : iso8601-python
BuildRequires : jsonschema-python
BuildRequires : os-testr-python
BuildRequires : oslo.log-python
BuildRequires : paramiko-python
BuildRequires : pbr
BuildRequires : pbr-python
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : six
BuildRequires : six-python

%description
===========
tempest-lib
===========
OpenStack Functional Testing Library
* Free software: Apache license
* Documentation: http://docs.openstack.org/developer/tempest-lib
* Source: http://git.openstack.org/cgit/openstack/tempest-lib
* Bugs: http://bugs.launchpad.net/tempest

%package bin
Summary: bin components for the tempest-lib package.
Group: Binaries

%description bin
bin components for the tempest-lib package.


%package python
Summary: python components for the tempest-lib package.
Group: Default
Requires: six-python
Requires: fixtures-python
Requires: iso8601-python
Requires: pbr-python
Requires: oslo.log-python
Requires: os-testr-python
Requires: paramiko-python
Requires: jsonschema-python

%description python
python components for the tempest-lib package.


%prep
%setup -q -n tempest-lib-0.9.0

%build
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/skip-tracker

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
