#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : tempest-lib
Version  : 1.0.0
Release  : 31
URL      : http://tarballs.openstack.org/tempest-lib/tempest-lib-1.0.0.tar.gz
Source0  : http://tarballs.openstack.org/tempest-lib/tempest-lib-1.0.0.tar.gz
Summary  : OpenStack Functional Testing Library
Group    : Development/Tools
License  : Apache-2.0
Requires: tempest-lib-bin
Requires: tempest-lib-python
Requires: Babel
Requires: fixtures
Requires: httplib2
Requires: iso8601
Requires: jsonschema
Requires: os-testr
Requires: oslo.log
Requires: paramiko
Requires: pbr
Requires: six
BuildRequires : configparser-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
===========
tempest-lib
===========
OpenStack Functional Testing Library
* Free software: Apache license
* Documentation: http://docs.openstack.org/developer/tempest-lib
* Source: http://git.openstack.org/cgit/openstack/tempest-lib
* Bugs: http://bugs.launchpad.net/tempest

%package bin
Summary: bin components for the tempest-lib package.
Group: Binaries

%description bin
bin components for the tempest-lib package.


%package python
Summary: python components for the tempest-lib package.
Group: Default

%description python
python components for the tempest-lib package.


%prep
%setup -q -n tempest-lib-1.0.0

%build
export LANG=C
export SOURCE_DATE_EPOCH=1489335372
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1489335372
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/check-uuid
/usr/bin/skip-tracker

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
